apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: installed-state-istiocontrolplane-default
  namespace: istio-system
spec:
  profile: default
  meshConfig:
    trustDomain: cluster1
    accessLogFile: /dev/stdout
    enableAutoMtls: true
    defaultConfig:
      envoyMetricsService:
        address: enterprise-agent.gloo-mesh:9977
      envoyAccessLogService:
        address: enterprise-agent.gloo-mesh:9977
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
        GLOO_MESH_CLUSTER_NAME: cluster1
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: cluster1
      network: network1
      meshNetworks:
        network1:
          endpoints:
          - fromRegistry: cluster1
          gateways:
          - registryServiceName: istio-ingressgateway.istio-system.svc.cluster.local
            port: 443
        vm-network:
  components:
    ingressGateways:
    - name: istio-ingressgateway
      label:
        topology.istio.io/network: network1
      enabled: true
      k8s:
        env:
          # sni-dnat adds the clusters required for AUTO_PASSTHROUGH mode
          - name: ISTIO_META_ROUTER_MODE
            value: "sni-dnat"
          # traffic through this gateway should be routed inside the network
          - name: ISTIO_META_REQUESTED_NETWORK_VIEW
            value: network1
        service:
          ports:
            - name: http2
              port: 80
              targetPort: 8080
            - name: https
              port: 443
              targetPort: 8443
            - name: tcp-status-port
              port: 15021
              targetPort: 15021
            - name: tls
              port: 15443
              targetPort: 15443
            - name: tcp-istiod
              port: 15012
              targetPort: 15012
            - name: tcp-webhook
              port: 15017
              targetPort: 15017
    pilot:
      k8s:
        env:
          - name: PILOT_SKIP_VALIDATE_TRUST_DOMAIN
            value: "true"
        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: istiod
          patches:
          # override istiod cacerts volume
          - path: spec.template.spec.volumes[name:cacerts]
            value: 
              name: cacerts
              secret: null
              emptyDir:
                medium: Memory
          # override istiod istiod-agent container to use Solo.io istiod-agent build
          - path: spec.template.spec.containers[1]
            value: 
              name: istiod-agent
              image: gcr.io/gloo-mesh/istiod-agent:1.2.27
              imagePullPolicy: IfNotPresent
              volumeMounts:
              - mountPath: /etc/cacerts
                name: cacerts
              args: 
              - sidecar
              env:
              - name: PILOT_CERT_PROVIDER
                value: istiod
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.name
              - name: POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
              - name: SERVICE_ACCOUNT
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: spec.serviceAccountName
          # override istiod istiod-agent-init init-container to use Solo.io istiod-agent-init build
          - path: spec.template.spec.initContainers
            value: 
            - name: istiod-agent-init
              image: gcr.io/gloo-mesh/istiod-agent:1.2.27
              imagePullPolicy: IfNotPresent
              volumeMounts:
              - mountPath: /etc/cacerts
                name: cacerts
              args: 
              - init-container
              env:
              - name: PILOT_CERT_PROVIDER
                value: istiod
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.name
              - name: POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
              - name: SERVICE_ACCOUNT
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: spec.serviceAccountName 