apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: virtual-mesh
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: "default"
  source:
    repoURL: https://github.com/willowmck/gloo-mesh-demo
    targetRevision: HEAD
    path: 01/argo/mgmt/kustomize/
  destination:
    server: https://kubernetes.default.svc
    namespace: "istio-system"
  syncPolicy:
    automated:
      prune: false
      selfHeal: false