apiVersion: networking.enterprise.mesh.gloo.solo.io/v1beta1
kind: WasmDeployment
metadata:
  name: ratings-wasm
  namespace: gloo-mesh
spec:
  filters:
  - filterContext: SIDECAR_INBOUND
    localPathSource: /opt/filters/wasm/hellofilter.wasm  # File needs to be available as container mount
    rootId: "add_header"
  workloadSelector:
  - kubeWorkloadMatcher:
      clusters:
      - cluster1
      labels:
        app: ratings
        version: v1
      namespaces:
      - default
