apiVersion: rbac.enterprise.mesh.gloo.solo.io/v1
kind: Role
metadata:
  name: infosec-
  namespace: gloo-mesh
spec:
  virtualDestinationScopes:
    - destinationSelectors:
        - kubeServiceMatcher:
            clusters:
              - '*'
            labels:
              '*': '*'
            namespaces:
              - '*'
          kubeServiceRefs:
            services:
              - clusterName: '*'
                name: '*'
                namespace: '*'
      destinations:
        - kubeService:
            clusterName: '*'
            name: '*'
            namespace: '*'
      meshRefs:
        - name: '*'
          namespace: '*'
      virtualMeshRefs:
        - name: '*'
          namespace: '*'
  routeScopes:
    - kubeServiceRefs:
        - clusterName: '*'
          name: '*'
          namespace: '*'
      routeTableSelectors:
        - namespaces:
            - '*'
      staticDestinationSelectors:
        - labels:
            '*': '*'
      virtualDestinationSelectors:
        - namespaces:
            - '*'
  wasmDeploymentScopes:
    - workloadSelectors:
        - kubeWorkloadMatcher:
            clusters:
              - '*'
            labels:
              '*': '*'
            namespaces:
              - '*'
  accessLogRecordScopes:
    - workloadSelectors:
        - kubeWorkloadMatcher:
            clusters:
              - '*'
            labels:
              '*': '*'
            namespaces:
              - '*'
  virtualHostScopes:
    - domains:
        - '*'
  accessPolicyScopes:
    - destinationSelectors:
        - kubeServiceMatcher:
            clusters:
              - '*'
            labels:
              '*': '*'
            namespaces:
              - '*'
          kubeServiceRefs:
            services:
              - clusterName: '*'
                name: '*'
                namespace: '*'
          virtualDestinationMatcher:
            labels:
              '*': '*'
            namespaces:
              - '*'
          virtualDestinationRefs:
            virtualDestinations:
              - name: '*'
                namespace: '*'
      identitySelectors:
        - kubeIdentityMatcher:
            clusters:
              - '*'
            namespaces:
              - '*'
          kubeServiceAccountRefs:
            serviceAccounts:
              - clusterName: '*'
                name: '*'
                namespace: '*'
  virtualMeshScopes:
    - meshRefs:
        - name: '*'
          namespace: '*'
      virtualMeshActions:
        - ALL
  virtualGatewayScopes:
    - ingressGatewaySelectors:
        - destinationSelectors:
            - kubeServiceMatcher:
                clusters:
                  - '*'
                labels:
                  '*': '*'
                namespaces:
                  - '*'
              kubeServiceRefs:
                services:
                  - clusterName: '*'
                    name: '*'
                    namespace: '*'
          portName: '*'
      virtualHostSelectors:
        - namespaces:
            - '*'
